/**
 * WASM module loader for Matcha2D.
 *
 * Loads the Emscripten-compiled Box2D WASM module and provides typed
 * TypeScript wrapper methods around the C bridge API.
 *
 * The Emscripten module is built with MODULARIZE=1 + EXPORT_ES6=1,
 * producing a default export function that returns Promise<Module>.
 */

import type { ContactManifold, MatchaBuffers } from '@matcha2d/types'
import { MAX_VERTICES_PER_SHAPE } from '@matcha2d/types'

// Emscripten module interface — matches the shape produced by
// MODULARIZE=1 + EXPORT_ES6=1 builds.
interface EmscriptenModule {
  HEAPF32: Float32Array
  HEAPU8: Uint8Array
  HEAP32: Int32Array
  cwrap(
    name: string,
    returnType: string | null,
    argTypes: string[],
  ): (...args: unknown[]) => unknown
  _malloc(size: number): number
  _free(ptr: number): void
}

// The glue module is generated by Emscripten at build time.
// We use a dynamic import with a type assertion since the file
// doesn't exist until the WASM build runs.
// eslint-disable-next-line @typescript-eslint/consistent-type-imports
type ModuleFactory = () => Promise<EmscriptenModule>

async function loadEmscriptenModule(): Promise<EmscriptenModule> {
  // The .js glue file lives at packages/core/wasm/build/box2d.js
  // relative to this source file (packages/core/src/wasm/).
  // It is produced by the Emscripten build pipeline (Plan 01).
  // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-argument
  const mod = await import(/* webpackIgnore: true */ '../../wasm/build/box2d.js')
  // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-unsafe-member-access
  return (mod.default as ModuleFactory)()
}

/**
 * Typed wrapper around the WASM C bridge functions.
 *
 * Each method corresponds to a WASM_EXPORT function from wasm_bridge.h:
 * b2_init, b2_destroy, b2_sync_bodies, b2_sync_shapes, b2_step,
 * b2_read_bodies, b2_get_contacts.
 */
export interface WasmInstance {
  /** Create a Box2D world. Returns world handle or -1 on failure. */
  init(gravityX: number, gravityY: number, maxBodies: number): number

  /** Destroy a Box2D world. */
  destroy(worldHandle: number): void

  /** Push SoA body data into WASM linear memory for Box2D. */
  syncBodies(worldHandle: number, buffers: MatchaBuffers, count: number): void

  /** Push SoA shape data into WASM linear memory for Box2D. */
  syncShapes(worldHandle: number, buffers: MatchaBuffers, count: number): void

  /** Advance simulation by one time step. */
  step(worldHandle: number, dt: number, subSteps: number): void

  /** Read updated body state from WASM back into JS SoA buffers. */
  readBodies(worldHandle: number, buffers: MatchaBuffers, count: number): void

  /** Read contact manifolds from the WASM world. */
  getContacts(worldHandle: number): ContactManifold[]

  /** Free all WASM-allocated memory. */
  dispose(): void
}

// Typed wrappers around cwrap results.
type CwrapInit = (gx: number, gy: number, max: number) => number
type CwrapDestroy = (handle: number) => void
type CwrapSyncBodies = (
  handle: number,
  posX: number, posY: number,
  velX: number, velY: number,
  angle: number, angVel: number,
  mass: number, invMass: number,
  inertia: number, invInertia: number,
  flags: number,
  count: number,
) => void
type CwrapSyncShapes = (
  handle: number,
  posX: number, posY: number, angle: number,
  halfExtentX: number, halfExtentY: number,
  shapeType: number,
  shapeRadius: number,
  shapeVertexCount: number,
  shapeVerticesX: number, shapeVerticesY: number,
  count: number,
) => void
type CwrapStep = (handle: number, dt: number, subSteps: number) => void
type CwrapReadBodies = (
  handle: number,
  posX: number, posY: number,
  velX: number, velY: number,
  angle: number, angVel: number,
  count: number,
) => void
type CwrapGetContactCount = (handle: number) => number
type CwrapGetContacts = (
  handle: number,
  bodyA: number, bodyB: number,
  nx: number, ny: number,
  px: number, py: number,
  penetration: number,
  maxContacts: number,
) => void

/** Safe cwrap wrapper that avoids the generic constraint issue. */
function wrapCwrap<T>(
  Module: EmscriptenModule,
  name: string,
  returnType: string | null,
  argTypes: string[],
): T {
  // eslint-disable-next-line @typescript-eslint/no-unsafe-return, @typescript-eslint/no-explicit-any
  return Module.cwrap(name, returnType, argTypes) as any as T
}

/**
 * Load the WASM module and return a typed WasmInstance.
 *
 * The returned instance wraps raw C bridge calls with clean TypeScript
 * signatures. SoA buffers are copied to/from WASM linear memory
 * using HEAPF32/HEAPU8 views.
 */
export async function loadWasmModule(): Promise<WasmInstance> {
  const Module = await loadEmscriptenModule()

  // Wrap C bridge functions using cwrap for type safety.
  const b2Init = wrapCwrap<CwrapInit>(Module, 'b2_init', 'number', ['number', 'number', 'number'])
  const b2Destroy = wrapCwrap<CwrapDestroy>(Module, 'b2_destroy', null, ['number'])
  const b2SyncBodies = wrapCwrap<CwrapSyncBodies>(Module, 'b2_sync_bodies', null, [
    'number', 'number', 'number', 'number', 'number', 'number', 'number',
    'number', 'number', 'number', 'number', 'number', 'number',
  ])
  const b2SyncShapes = wrapCwrap<CwrapSyncShapes>(Module, 'b2_sync_shapes', null, [
    'number', 'number', 'number', 'number', 'number', 'number',
    'number', 'number', 'number', 'number', 'number', 'number',
  ])
  const b2Step = wrapCwrap<CwrapStep>(Module, 'b2_step', null, ['number', 'number', 'number'])
  const b2ReadBodies = wrapCwrap<CwrapReadBodies>(Module, 'b2_read_bodies', null, [
    'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number',
  ])
  const b2GetContactCount = wrapCwrap<CwrapGetContactCount>(Module, 'b2_get_contact_count', 'number', ['number'])
  const b2GetContacts = wrapCwrap<CwrapGetContacts>(Module, 'b2_get_contacts', null, [
    'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number', 'number',
  ])

  // Track persistent WASM-allocated memory for cleanup.
  // Temporary allocations (sync/read calls) are freed immediately after use.
  const persistentAllocs: number[] = []

  /**
   * Allocate a typed array in WASM memory and copy data from a JS array.
   * Returns the byte offset (pointer) into WASM HEAP.
   * The caller is responsible for freeing the allocation via Module._free().
   */
  function allocAndCopy(
    source: Float32Array | Uint8Array | Int32Array,
    count: number,
  ): number {
    const byteSize = count * source.BYTES_PER_ELEMENT
    const ptr = Module._malloc(byteSize)
    if (ptr === 0) {
      throw new Error('WASM: malloc returned NULL — out of memory')
    }
    // Create a typed array view over WASM memory at the allocated pointer.
    // We use explicit constructors because TS can't infer constructability
    // from source.constructor (which is typed as Function).
    let heapView: Float32Array | Uint8Array | Int32Array
    if (source instanceof Float32Array) {
      heapView = new Float32Array(Module.HEAPU8.buffer, ptr, count)
    } else if (source instanceof Int32Array) {
      heapView = new Int32Array(Module.HEAPU8.buffer, ptr, count)
    } else {
      heapView = new Uint8Array(Module.HEAPU8.buffer, ptr, count)
    }
    heapView.set(source.subarray(0, count))
    return ptr
  }

  /**
   * Read data from WASM HEAP back into a JS typed array.
   */
  function readFromHeap(
    dest: Float32Array | Int32Array,
    heapPtr: number,
    count: number,
  ): void {
    if (dest instanceof Float32Array) {
      const heapView = new Float32Array(Module.HEAPU8.buffer, heapPtr, count)
      dest.set(heapView.subarray(0, count))
    } else if (dest instanceof Int32Array) {
      const heapView = new Int32Array(Module.HEAPU8.buffer, heapPtr, count)
      dest.set(heapView.subarray(0, count))
    }
  }

  /** Free a list of WASM heap pointers. */
  function freeMany(ptrs: number[]): void {
    for (const ptr of ptrs) {
      Module._free(ptr)
    }
  }

  const instance: WasmInstance = {
    init(gravityX: number, gravityY: number, maxBodies: number): number {
      return b2Init(gravityX, gravityY, maxBodies)
    },

    destroy(worldHandle: number): void {
      b2Destroy(worldHandle)
    },

    syncBodies(worldHandle: number, buffers: MatchaBuffers, count: number): void {
      const ptrPosX = allocAndCopy(buffers.positionX, count)
      const ptrPosY = allocAndCopy(buffers.positionY, count)
      const ptrVelX = allocAndCopy(buffers.velocityX, count)
      const ptrVelY = allocAndCopy(buffers.velocityY, count)
      const ptrAngle = allocAndCopy(buffers.angle, count)
      const ptrAngVel = allocAndCopy(buffers.angularVel, count)
      const ptrMass = allocAndCopy(buffers.mass, count)
      const ptrInvMass = allocAndCopy(buffers.invMass, count)
      const ptrInertia = allocAndCopy(buffers.inertia, count)
      const ptrInvInertia = allocAndCopy(buffers.invInertia, count)
      const ptrFlags = allocAndCopy(buffers.flags, count)

      b2SyncBodies(
        worldHandle,
        ptrPosX, ptrPosY,
        ptrVelX, ptrVelY,
        ptrAngle, ptrAngVel,
        ptrMass, ptrInvMass,
        ptrInertia, ptrInvInertia,
        ptrFlags,
        count,
      )

      // Free temporary allocations immediately after the call
      freeMany([ptrPosX, ptrPosY, ptrVelX, ptrVelY, ptrAngle, ptrAngVel, ptrMass, ptrInvMass, ptrInertia, ptrInvInertia, ptrFlags])
    },

    syncShapes(worldHandle: number, buffers: MatchaBuffers, count: number): void {
      const ptrPosX = allocAndCopy(buffers.positionX, count)
      const ptrPosY = allocAndCopy(buffers.positionY, count)
      const ptrAngle = allocAndCopy(buffers.angle, count)
      const ptrHalfExtentX = allocAndCopy(buffers.halfExtentX, count)
      const ptrHalfExtentY = allocAndCopy(buffers.halfExtentY, count)
      const ptrShapeType = allocAndCopy(buffers.shapeType, count)
      const ptrShapeRadius = allocAndCopy(buffers.shapeRadius, count)
      const ptrShapeVertexCount = allocAndCopy(buffers.shapeVertexCount, count)

      // Vertex arrays are capacity * MAX_VERTICES_PER_SHAPE
      const vertexCount = count * MAX_VERTICES_PER_SHAPE
      const ptrVerticesX = allocAndCopy(buffers.shapeVerticesX, vertexCount)
      const ptrVerticesY = allocAndCopy(buffers.shapeVerticesY, vertexCount)

      b2SyncShapes(
        worldHandle,
        ptrPosX, ptrPosY, ptrAngle,
        ptrHalfExtentX, ptrHalfExtentY,
        ptrShapeType,
        ptrShapeRadius,
        ptrShapeVertexCount,
        ptrVerticesX, ptrVerticesY,
        count,
      )
    },

    step(worldHandle: number, dt: number, subSteps: number): void {
      b2Step(worldHandle, dt, subSteps)
    },

    readBodies(worldHandle: number, buffers: MatchaBuffers, count: number): void {
      // Allocate output arrays in WASM memory (zeroed)
      const ptrPosX = allocAndCopy(new Float32Array(count), count)
      const ptrPosY = allocAndCopy(new Float32Array(count), count)
      const ptrVelX = allocAndCopy(new Float32Array(count), count)
      const ptrVelY = allocAndCopy(new Float32Array(count), count)
      const ptrAngle = allocAndCopy(new Float32Array(count), count)
      const ptrAngVel = allocAndCopy(new Float32Array(count), count)

      b2ReadBodies(
        worldHandle,
        ptrPosX, ptrPosY,
        ptrVelX, ptrVelY,
        ptrAngle, ptrAngVel,
        count,
      )

      // Copy results back to JS buffers
      readFromHeap(buffers.positionX, ptrPosX, count)
      readFromHeap(buffers.positionY, ptrPosY, count)
      readFromHeap(buffers.velocityX, ptrVelX, count)
      readFromHeap(buffers.velocityY, ptrVelY, count)
      readFromHeap(buffers.angle, ptrAngle, count)
      readFromHeap(buffers.angularVel, ptrAngVel, count)
    },

    getContacts(worldHandle: number): ContactManifold[] {
      const contactCount = b2GetContactCount(worldHandle)
      if (contactCount === 0) return []

      // Allocate output arrays in WASM memory
      const ptrBodyA = allocAndCopy(new Int32Array(contactCount), contactCount)
      const ptrBodyB = allocAndCopy(new Int32Array(contactCount), contactCount)
      const ptrNx = allocAndCopy(new Float32Array(contactCount), contactCount)
      const ptrNy = allocAndCopy(new Float32Array(contactCount), contactCount)
      const ptrPx = allocAndCopy(new Float32Array(contactCount), contactCount)
      const ptrPy = allocAndCopy(new Float32Array(contactCount), contactCount)
      const ptrPen = allocAndCopy(new Float32Array(contactCount), contactCount)

      b2GetContacts(
        worldHandle,
        ptrBodyA, ptrBodyB,
        ptrNx, ptrNy,
        ptrPx, ptrPy,
        ptrPen,
        contactCount,
      )

      // Read back from WASM memory
      const heapBodyA = new Int32Array(Module.HEAPU8.buffer, ptrBodyA, contactCount)
      const heapBodyB = new Int32Array(Module.HEAPU8.buffer, ptrBodyB, contactCount)
      const heapNx = new Float32Array(Module.HEAPU8.buffer, ptrNx, contactCount)
      const heapNy = new Float32Array(Module.HEAPU8.buffer, ptrNy, contactCount)
      const heapPx = new Float32Array(Module.HEAPU8.buffer, ptrPx, contactCount)
      const heapPy = new Float32Array(Module.HEAPU8.buffer, ptrPy, contactCount)
      const heapPen = new Float32Array(Module.HEAPU8.buffer, ptrPen, contactCount)

      // Build ContactManifold array
      const manifolds: ContactManifold[] = []
      for (let i = 0; i < contactCount; i++) {
        manifolds.push({
          bodyA: heapBodyA[i] as unknown as ContactManifold['bodyA'],
          bodyB: heapBodyB[i] as unknown as ContactManifold['bodyB'],
          normal: { x: heapNx[i], y: heapNy[i] },
          contacts: [{
            localA: { x: 0, y: 0 },
            localB: { x: heapPx[i], y: heapPy[i] },
            penetration: heapPen[i],
          }],
        })
      }

      return manifolds
    },

    dispose(): void {
      for (const ptr of persistentAllocs) {
        Module._free(ptr)
      }
      persistentAllocs.length = 0
    },
  }

  return instance
}
